#!/bin/bash
# scripts/prepare-photo-assets.sh
#
# One-time asset prep for the About-page recognition photos and the personal
# gallery. Run manually from the repo root; not part of `npm run build`.
#
# Source: `_Sheng Chang Photos/` (repo root, untracked). Excludes the 3
# Arcadia Public Library archive photos (no reproduction permission — see
# docs/superpowers/specs/2026-08-25-photo-gallery-and-recognition-design.md)
# and the 8 photos selected for the About page (handled separately below, at
# higher quality since they're few and framed/read-up-close).
set -euo pipefail

SRC="_Sheng Chang Photos"
RECOGNITION_DIR="public/images/recognition"
GALLERY_THUMB_DIR="public/images/gallery/thumb"
GALLERY_FULL_DIR="public/images/gallery/full"

mkdir -p "$RECOGNITION_DIR" "$GALLERY_THUMB_DIR" "$GALLERY_FULL_DIR"

# --- 8 selected photos for the About page, explicit source -> target name ---
# Using parallel indexed arrays for bash 3.2 compatibility
RECOGNITION_SRC=(
  "IMG_1220.HEIC"
  "IMG_1222.HEIC"
  "IMG_1233.HEIC"
  "IMG_1240.heic"
  "IMG_1181 copy.HEIC"
  "IMG_1227 copy.HEIC"
  "IMG_1259 copy.HEIC"
  "IMG_1182 copy.HEIC"
)
RECOGNITION_DST=(
  "congressional-proclamation-1988.jpg"
  "la-county-commendation-1988.jpg"
  "certificate-of-commendation-1988.jpg"
  "alumni-certificate-2005.jpg"
  "banquet-speech-1987.jpg"
  "welcome-delegation.jpg"
  "plaque-presentation-1989.jpg"
  "culture-symposium.jpg"
)

for i in "${!RECOGNITION_SRC[@]}"; do
  src_name="${RECOGNITION_SRC[$i]}"
  target="${RECOGNITION_DST[$i]}"
  sips -s format jpeg -Z 1200 "$SRC/$src_name" --out "$RECOGNITION_DIR/$target" >/dev/null
  echo "recognition: $src_name -> $target"
done

# --- Everything else, minus the blocked photos and the 8 selected above ---
# The first 3 are the Arcadia Public Library archive photos (no reproduction
# permission). The next 4 were cut after publication review found the
# owner's home address and third-party private correspondence in them
# (ids 049/063/068/069 in the gallery that shipped before this fix) — do
# not remove them from this list without a fresh privacy review.
BLOCKED=(
  "1475.jpg" "1497.jpg" "1508.jpg"
  "IMG_1171.HEIC" "IMG_1223 copy.HEIC" "IMG_1230.HEIC" "IMG_1232 copy.HEIC"
)
SELECTED=("${RECOGNITION_SRC[@]}")
EXCLUDE=("${BLOCKED[@]}" "${SELECTED[@]}" ".DS_Store")

is_excluded() {
  local name="$1"
  for x in "${EXCLUDE[@]}"; do
    [ "$name" = "$x" ] && return 0
  done
  return 1
}

i=0
> src/data/galleryPhotos.ts.ids
for f in "$SRC"/*; do
  name=$(basename "$f")
  is_excluded "$name" && continue
  i=$((i+1))
  id=$(printf "%03d" "$i")
  sips -s format jpeg -Z 480 "$f" --out "$GALLERY_THUMB_DIR/$id.jpg" >/dev/null
  sips -s format jpeg -Z 1400 "$f" --out "$GALLERY_FULL_DIR/$id.jpg" >/dev/null
  echo "$id" >> src/data/galleryPhotos.ts.ids
done

count=$(wc -l < src/data/galleryPhotos.ts.ids | tr -d ' ')
echo "gallery: $count photos"

{
  echo "// Generated by scripts/prepare-photo-assets.sh — do not hand-edit."
  echo "export interface GalleryPhoto { id: string }"
  echo ""
  echo "export const galleryPhotos: GalleryPhoto[] = ["
  while read -r id; do
    echo "  { id: '$id' },"
  done < src/data/galleryPhotos.ts.ids
  echo "];"
  echo ""
  echo "export const galleryPhotoCount = galleryPhotos.length;"
} > src/data/galleryPhotos.ts

rm src/data/galleryPhotos.ts.ids
echo "wrote src/data/galleryPhotos.ts with $count entries"
